language: go
go:
- 1.7.4
- tip
before_deploy:
- go install -v ./...
- ls -a .
- ls -a $GOPATH/bin
deploy:
  provider: releases
  api_key:
    secure: ACom00uBgH6UZaFhSALmmTBrPaH8wGs4GVsX3eIp172tZXhdxBxDlrGuAaXlmXhEaTaQ9V7W/84WEpEJUzpTgTfs6UDMh3Sx0l4shpMloZmgxjhKRLxKO2pKJrpOknDjR3011+3UckDDvFgLsDoZmvjMHgap0dTSsWxT+TjD9tdrq9wwY/0WXF5bdv8T0sBF9NBnObfW6JzGsRLxI1DJHDZbyVKVPqKCqIcFHpzyrUNsiLnOvD2wM0bRHUGdzvZHXpx66wT4uKqQ70LUj3SYN+n8pFP5DIU9Kmc/59s+TZp6HE/gjJBhfmwBVh818kJLBMPG31PhHm1rzBdvgfv2tLCjJv4Vwkk35bsf9965QScLgE1BJzzuKb5+WCD0uCioC87gzEz+vzuTOPHJgAJSqJdvZR2qRvd/3naQO8ZxZ5iJ/JmBYOz2Ugsn53K695q3RfkOadzom54/9CMOiOgNoplf0HHamuzUHuw7l+/vUzM6KVN6Ap0bPrxkr7wq3BAKq6YQ/yuzaHNX4CjNejS3Q2XTwoW14azQu7FNXS0zJRdvGAi4Kr6sbHY+cLFw9ZgsQV/blVS9vfgTJteLJE9cBpNe89r9nsG+ebNnxJ0eMUxPPtqL16bRLMs2Pexti69C6x/ooc30BRCx4KRgKq7Jg6khYhermajV5vvF5sc4Idw=
  file: $GOPATH/bin/terraform-provider-amaxo-aws
  skip_cleanup: true
  on:
    tags: true
